
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 13 20:32:13 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 36;
  public static final int CHAR = 50;
  public static final int CONST = 7;
  public static final int LESSE = 32;
  public static final int GRT = 29;
  public static final int LPAREN = 44;
  public static final int SEMI = 39;
  public static final int CONTINUE = 17;
  public static final int LESS = 31;
  public static final int MINUS = 22;
  public static final int RPAREN = 45;
  public static final int AND = 33;
  public static final int RECORD = 21;
  public static final int OR = 34;
  public static final int BOOL = 51;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int DIV = 25;
  public static final int PLUS = 23;
  public static final int ASSIGN = 35;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 14;
  public static final int EQUAL = 27;
  public static final int GRTE = 30;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 48;
  public static final int MOD = 26;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int COLON = 38;
  public static final int LBRACE = 42;
  public static final int ELSE = 6;
  public static final int LSQUARE = 46;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int RSQUARE = 47;
  public static final int WHILE = 10;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int NOTEQ = 28;
}

